/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include "timer.h"
#include "led_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

led_typedef_t ONBOARD_LED;

void SystemClock_Config(void);
void config_onboard_led(void);
void toggle_onboard_led(void);

int main(void)
{
    SystemClock_Config();
    Timer_Init();

    config_onboard_led();

    Timer_Set(TIMER_ONBOARD_LED, 500, toggle_onboard_led, TIMER_MODE_ALWAYS);

    /* Loop forever */
    while(1)
    {
        Timer_SM();
    }
}

void SystemClock_Config(void)
{
    /* Configure System Clock to 64 MHz with external crystal oscillator */

    /* Steps to configure System Clock */
    /*
       1. Enable HSE and wait to become ready;
       2. Set the Power Enable bit;
       3. Configure the Flash Latency for the clock frequency;
       4. Configure the prescalers of HCLK, PCLK1 and PCLK2;
       5. Configure PLL;
       6. Enable PLL and wait to become ready;
       7. Select the Clock Source and wait to become ready.
    */

    /* 1. Enable HSE and wait for HSE to become ready */
    RCC->CR |= RCC_CR_HSEON;
    while( !(RCC->CR & RCC_CR_HSERDY) );// when done, HSERDY is set

    /* 2. Set the Power Enable bit */
    RCC->APB1ENR |= RCC_APB1ENR_PWREN;

    /* 3. Configure the FLASH PREFETCH and the LATENCY Related Settings */
    /*
       FLASH_ACR_LATENCY_0 if 0 < SYSCLK <= 24 MHz
       FLASH_ACR_LATENCY_1 if 24 MHz < SYSCLK <= 48 MHz
       FLASH_ACR_LATENCY_2 if 48 MHz < SYSCLK <= 72 MHz
     */
    FLASH->ACR |= FLASH_ACR_LATENCY_2;


    /* 4. Configure the PRESCALERS HCLK, PCLK1, PCLK2 */

    // AHB Prescaler
//    RCC->CFGR |= RCC_CFGR_HPRE_DIV1;

    // APB1 Prescaler
    RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;

    // APB2 Prescaler
//    RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;


    /* 5. Configure the MAIN PLL */
    /*
         HSE External Crystal Clock: 8 MHz
         PLL input div clock: DIV1
         PLL internal mult clock: MULL8 (clock at PLL output: 64 MHz)
         AHB presc.: 1
         APB1 presc: min: 2: max APB1 clock: 32 MHz
         APB2 presc: 1       max APB2 clock: 64 MHz
     */
    RCC->CFGR |= RCC_CFGR_PLLSRC;               // Select HSE as PLL input clock
//    RCC->CFGR |= RCC_CFGR_PLLXTPRE_HSE;         // Do not divide PLL input clock
//    RCC->CFGR |= RCC_CFGR_PLLXTPRE_HSE_DIV2;    // Divide by 2 PLL input clock
    RCC->CFGR |= RCC_CFGR_PLLMULL8;             // Multiply by 8 PLL internal clock


    /* 6. Enable PLL and wait for PLL to become ready */
    RCC->CR |= RCC_CR_PLLON;
    while( !(RCC->CR & RCC_CR_PLLRDY) );

    /* 7. Select the System Clock Source and wait to become ready */
    RCC->CFGR |= RCC_CFGR_SW_PLL;               // Select PLL as System Clock
    while( (RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL );

}// end SystemClock_Config

void config_onboard_led(void)
{
    ONBOARD_LED.GPIO_PORT = GPIOC;
    ONBOARD_LED.GPIO_PIN = 13;
    ONBOARD_LED.active_level = LED_ACTIVE_LOW;
    ONBOARD_LED.output_mode = OUTPUT_PUSH_PULL;

    led_driver_init(&ONBOARD_LED);
    led_driver_off(&ONBOARD_LED);
}

void toggle_onboard_led(void)
{
    led_driver_toggle(&ONBOARD_LED);
}
