/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "mc_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint32_t value);


int main(void)
{


	GPIO_Init(PA, 0, IN, IN_PP);
	GPIO_Init(PC, 13, OUT50, OUT_GP_PP);


	while(1)
	{
		if(GPIO_Read(PA, 0))
		{
			GPIO_Toggle(PC, 13);
			delay(0xFFFF);
		}
		else
		{
			GPIO_Write(PC, 13, 0);
		}


	}
}

void delay(uint32_t value)
{
	for(uint32_t i = 0; i < value; i++);
}
