/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

#include "mc_gpio_driver.h"

#define LED_GPIO_Port PC
#define LED_GPIO_Pin  13

#define BUTTON_GPIO_Port PA
#define BUTTON_GPIO_Pin	 0

#define LED_STATE_ON 	0
#define LED_STATE_OFF	1
#define LED_SET_STATE(LED_STATE) GPIO_Write(LED_GPIO_Port,LED_GPIO_Pin, LED_STATE)
#define LED_GET_STATE GPIO_Read(LED_GPIO_Port,LED_GPIO_Pin)

#define READ_BTN GPIO_Read(BUTTON_GPIO_Port, BUTTON_GPIO_Pin)

/* Functions Prototypes */
void delay(uint32_t value);

/* Mains function */
int main(void)
{


	GPIO_Init(LED_GPIO_Port, LED_GPIO_Pin, OUT50, OUT_GP_PP);
	GPIO_Init(BUTTON_GPIO_Port, BUTTON_GPIO_Pin, IN, IN_PP);

	// Configure PA0 as rising exti interrupt
	__disable_irq(); // disables all interrupts
	AFIO->EXTICR[0] = 0x00; // EXTI Configuration Register; EXTI[0] : EXTI0;  0b0000: PA0 pin
	EXTI->IMR	|= (1<<0); // Interrupt Mask Register: bit set: Line x is not masked
	EXTI->RTSR 	|= (1<<0); // Rising Trigger Selection Register: bit set: Rising Trigger enabled
	__NVIC_EnableIRQ(EXTI0_IRQn);
	__enable_irq(); // enables all interrupts

	while(1)
	{

	}
}


/* Functions */

void delay(uint32_t value)
{
	for(uint32_t i = 0; i < value; i++);
}

void EXTI0_IRQHandler() // same func name as in startup_stm32f103c8tx.s file
{
	EXTI->PR |= (1<<0); // clear interrupt flag

	LED_SET_STATE(!LED_GET_STATE);

}
