/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include "sys_clock.h"
#include "timer.h"
#include "leds.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    Sys_Clock_Init();
    Timer_Init();
    Leds_Init();

    Timer_Set(TIMER_GREEN_LED,    1000,  Leds_Toggle_Green_Led,    TIMER_MODE_ALWAYS);

    Timer_Set(TIMER_RED_LED, 100, Leds_Toggle_Red_Led, TIMER_MODE_ALWAYS);

    uint32_t millis_counter = 0;

    while(1)
    {
        Timer_SM();

        if(Timer_Get_Sys_Tick() - millis_counter > 10000)
        {
            Timer_Continue(TIMER_RED_LED);
            millis_counter = Timer_Get_Sys_Tick();
        }
        else if(Timer_Get_Sys_Tick() - millis_counter > 5000)
        {
            Timer_Stop(TIMER_RED_LED);
        }
    }// end while (1)

}// end main

