/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include "main.h"
#include "sys_clock.h"
#include "timer.h"
#include "gpio.h"
#include "exti.h"
#include "button.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define LED_ONBOARD_PORT    GPIOC
#define LED_ONBOARD_PIN     13

#define LED_RED_PORT        GPIOB
#define LED_RED_PIN         12

#define LED_GREEN_PORT      GPIOB
#define LED_GREEN_PIN       13



void Config_Leds(void);
void error_handler();

void button0_short_callback();  // callback when short pressed Button0
void button0_long_callback();   // callback when long pressed Button0
void button0_long_release_callback(); // callback when released after long press

int main(void)
{
    Sys_Clock_Init();
    Timer_Init();
    Config_Leds();
    // Config BUTTON
    Button_config(BUTTON0, BUTTON0_PORT, BUTTON0_PIN, BUTTON_ACTIVE_LOW, 20, 1000,
            button0_short_callback, button0_long_callback, button0_long_release_callback);

    while(1)
    {
        Timer_SM();

    }// end while (1)

}// end main

void Config_Leds(void)
{
    // Config LEDs
    Gpio_Config(LED_ONBOARD_PORT, LED_ONBOARD_PIN, OUTPUT_OPEN_DRAIN);
    Gpio_Config(LED_RED_PORT, LED_RED_PIN, OUTPUT_PUSH_PULL);
    Gpio_Config(LED_GREEN_PORT, LED_GREEN_PIN, OUTPUT_PUSH_PULL);

    Gpio_Digital_Write(LED_ONBOARD_PORT, LED_ONBOARD_PIN, 1); // Turn Onboard Led OFF
}


void button0_short_callback()
{
    Gpio_Digital_Toggle(LED_RED_PORT, LED_RED_PIN);
}

void toggle_red_led()
{
    Gpio_Digital_Toggle(LED_RED_PORT, LED_RED_PIN);
}

void button0_long_callback()
{
    Timer_Set(TIMER_RED_LED, 100, toggle_red_led, TIMER_MODE_ALWAYS);
}

void button0_long_release_callback()
{
    Timer_Stop(TIMER_RED_LED);
}

/* BLOCK PROCESSOR IF ERROR OCCUR */
void error_handler()
{
    Exti_Disable_All_Lines();
    while(1)
    {
        Gpio_Digital_Toggle(LED_RED_PORT, LED_RED_PIN);
        Delay_ms(500);
        Gpio_Digital_Toggle(LED_RED_PORT, LED_RED_PIN);
        Delay_ms(500);
    }
}
