/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#define LED_ON	(  GPIOC->ODR &= ~(1<<13)  ) // LED ON when Pin is LOW
#define LED_OFF	(  GPIOC->ODR |=  (1<<13)  ) // LED OFF when Pin is HIGH

void led_init(void);
void delay(uint32_t value);

int main(void)
{

	led_init();

	while(1)
	{

		// ODR: Output Data Register
		LED_ON; 		// Set pin PC.13 HIGH
		delay(0xFFFFF);
		LED_OFF; 	// Set pin PC.13 LOW
		delay(0xFFFFF);

	}

	return 0;

}

void led_init(void)
{
	// GPIO bus is connected to APB2 peripheral clock
	// APB2ENR is the AP2 Enable Register (see reference manual)
	// IOPC EN bit is the 4th bit in the register
	// We set this bit with the mask (1 << 4), with bitwise OR operator:
	RCC->APB2ENR |= (1 << 4); // set IOPC bit of APB2EN register


	// Port configuration register (CR)
	// To contro PC.13, we need to see GPIOx_CRH register (pins 8 to 15)
	// This register uses 4 bits to configure the pin (2 ibts for MODE, 2 bits for CNF)
	// To configure PC.13 as Output push pull:
	// Set bits 21 and 20 (Output mode)
	// Set set bit 23 and reset bit 22 (Push pull)
	GPIOC->CRH |= 	(0b11 << 20); // Output mode
	GPIOC->CRH &=  ~(0b11 << 22); // Push Pull
}

void delay(uint32_t value)
{
	for(uint32_t i = 0; i < value; i++);
}
